version: "3.9"

services:

  base:
    # This is the container name
    container_name: cavli-test-base
    image: cavli-test-docker:base
    # This is the hostname of the container
    hostname: cavli-test
    entrypoint: /bin/bash -c "/opt/scripts/env_init.sh && while true; do sleep 10; done"
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime
      - /dev/bus/usb:/dev/bus/usb
    tty: true
    build:
      context: ./base

  cts:
    # This is the container name
    container_name: cqs290_cts
    image: cavli-test-docker:cqs290_cts
    entrypoint: /bin/bash -c "/opt/scripts/env_init.sh && while true; do sleep 10; done"
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - /dev:/dev 
      - /dev/bus/usb:/dev/bus/usb
    tty: true
    build:
      context: ./cts

  stick:
    # This is the container name
    container_name: stick_testtools
    image: cavli-test-docker:stick_testtools
    entrypoint: /bin/bash -c "/opt/scripts/env_init.sh && while true; do sleep 10; done"
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - /dev:/dev 
      - /dev/bus/usb:/dev/bus/usb
    tty: true
    build:
      context: ./targets/stick
