company:
  name: "JP Morgan Chase Bank N.A"
  font_size: 20

model:
  name: "STICK_401_GEN1"
  font_size: 16

font_bold: "DejaVuSans-Bold.ttf"
font_regular: "DejaVuSans.ttf"
code_font_size: 14

countries:
  - name: "CANADA"
    font_size: 18
    ices:
      standards: "CAN ICES-3 (B)/NMB-3(B)"
      cavli_code: "31113-CQS290NA"
      code: "33846-STICK401"
    culus:
      logo: "culus_ite_icon_100.png"
      code: "E336783"

  - name: "UNITED STATES"
    font_size: 18
    fcc:
      logo: "fcc_logo_40.png"
      cavli_code: "2BB64CQS290NA"
      code: "2BHXP-STICK401GEN1"
      statement: "fcc_statement_400_2.png"
    culus:
      logo: "culus_ite_icon_100.png"
      code: "E336783"
