
# Cool custom PS1 with Git branch and colors
parse_git_branch() {
  git branch 2>/dev/null | grep '*' | sed 's/* \(.*\)/ (\1)/'
}

export PS1="\[\e[1;32m\][CAVLI_TEST] \[\e[1;34m\]\w\[\e[1;33m\]\$(parse_git_branch)\[\e[0m\] \$\n"

alias adbd='adb wait-for-device; adb devices'
alias fastbootd='fastboot devices'
alias logcat='adb logcat -b all -v color,time'
alias broadcast='adb shell am broadcast -a'

alias reboot='echo Fuck you! Do not reboot this PC'

alias repo-clean='repo forall -c "git clean -fxd && git reset --hard"'

alias git-clean='git clean -fxd && git reset --hard'

alias flatbuild='qdl --storage emmc prog_firehose_ddr.elf rawprogram*.xml patch*.xml'

alias aosp-var_11='build/soong/soong_ui.bash --dumpvars-mode --vars'
alias aosp-var_14='get_build_var'

alias udev-reload='udevadm control --reload-rules && udevadm trigger'

alias protect-y='chattr +i'
alias protect-n='chattr -i'
