#!/bin/bash

echo ""
echo "# List all image:"
echo "    docker images"
echo ""
echo "# Rebuild services defined in docker-compose.yml"
echo "    docker-compose build --no-cache <services>"
echo "    docker-compose build <services>"
echo ""
echo "# Check stogare was be using"
echo "    docker system df"
echo ""
echo "# Clean up the cache"
echo "    docker builder prune -a"
echo ""
echo "# Running full system prune (containers, images, networks, volumes)"
echo "    docker system prune -af --volumes"
echo ""
echo "# Bringing down docker-compose stack (with volumes)"
echo "    cd <docker_directory>"
echo "    docker-compose down --volumes"
echo ""
echo "# Remove image"
echo "    docker images => get ID"
echo "    docker rmi <ID>"
